apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nexora
  labels:
    app.kubernetes.io/name: postgres-pvc
    app.kubernetes.io/part-of: nexora-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
